package com.smalik.invoker;

import java.util.Random;

public class RandomPersonGenerator {

    private Random random = new Random();

    public Person generate() {

        String name = scientists[random.nextInt(scientists.length)];
        String city = cities[random.nextInt(cities.length)];
        int age = random.nextInt(85) + 15;

        return new Person(name, city, age);
    }

    private String[] cities = {
            "New York City, United States",
            "Paris, France",
            "Rome, Italy",
            "London, United Kingdom",
            "Jerusalem, Israel",
            "Bangkok, Thailand",
            "Prague, Czech Republic",
            "Berlin, Germany",
            "Amsterdam, Netherlands",
            "Madrid, Spain",
            "Munich, Germany",
            "Vienna, Austria",
            "Washington DC, United States",
            "Brussels, Belgium",
            "Tel Aviv, Israel",
            "Barcelona, Spain",
            "Istanbul, Turkey",
            "Sydney, Australia",
            "Rio De Janeiro, Brazil",
            "Venice, Italy",
            "Budapest, Hungary",
            "Seville, Spain",
            "Granada, Spain",
            "San Francisco, United States",
            "Cape Town, South Africa",
            "Hong Kong, China",
            "Buenos Aires, Argentina",
            "Florence, Italy",
            "Tokyo, Japan",
            "Cairo, Egypt",
            "Toronto, Canada",
            "Athens, Greece",
            "Melbourne, Australia",
            "Kathmandu, Nepal",
            "Montreal, Canada",
            "Edinburgh, United Kingdom",
            "Hanoi, Vietnam",
            "Singapore",
            "Dublin, Ireland",
            "Mexico City, Mexico",
            "Krakow, Poland",
            "Las Vegas, United States",
            "Havana, Cuba",
            "Sarajevo, Bosnia and Herzegovina",
            "Los Angeles, United States",
            "Stockholm, Sweden",
            "Chicago, United States",
            "Lisbon, Portugal",
            "New Orleans, United States",
            "Ho Chi Minh City, Vietnam",
            "Marrakech, Morocco",
            "Kyoto, Japan",
            "Moscow, Russia",
            "Shanghai, China",
            "Seattle, United States",
            "Beijing, China",
            "Helsinki, Finland",
            "St. Petersburg, Russia",
            "Fes, Morocco",
            "Phnom Penh, Cambodia",
            "Cusco, Peru",
            "Varanasi, India",
            "Luang Prabang, Laos",
            "Dubrovnik, Croatia",
            "New Delhi, India",
            "Salvador Da Bahia, Brazil",
            "Kolkata, India",
            "Santiago, Chile",
            "Auckland, New Zealand",
            "Manila, Philippines",
            "Zanzibar, Tanzania",
            "Mumbai, India",
            "Hamburg, Germany",
            "Wellington, New Zealand",
            "Ljubljana, Slovenia",
            "Seoul, South Korea",
            "Taipei, Taiwan",
            "Tallinn, Estonia",
            "Lhasa, China",
            "Bled, Slovenia",
            "Siena, Italy",
            "Jaipur, India",
            "La Paz, Bolivia",
            "Quebec City, Canada",
            "Naples, Italy",
            "Heidelberg, Germany",
            "Panama City, Panama",
            "Monaco",
            "Quito, Ecuador",
            "Bern, Switzerland",
            "Cartagena, Colombia",
            "Hobart, Australia",
            "Valparaiso, Chile",
            "Christchurch, New Zealand",
            "Dakar, Senegal",
            "Bratislava, Slovakia",
            "Riga, Latvia",
            "Copenhagen, Denmark",
            "Sofia, Bulgaria",
            "Marseille, France",
            "Glasgow, United Kingdom",
            "San Juan, Puerto Rico",
            "Bath, United Kingdom",
            "Macau, China",
            "Hoi An, Vietnam",
            "Zagreb, Croatia",
            "Manchester, United Kingdom",
            "Antigua, Guatemala",
            "Reykjavik, Iceland",
            "Hiroshima, Japan",
            "Nairobi, Kenya",
            "Vilnius, Lithuania",
            "Bukhara, Uzbekistan",
            "Bucharest, Romania",
            "Carcassonne, France",
            "Lubeck, Germany",
            "Montevideo, Uruguay",
            "Yangon, Myanmar",
            "Belgrade, Serbia",
            "Dar Es Salaam , Tanzania",
            "Kiev, Ukraine",
            "Caracas, Venezuela",
            "Male, Maldives",
            "Tbilisi, Georgia",
            "Suva, Fiji",
            "Ushuaia, Argentina",
            "Bogota, Colombia",
            "Minsk, Belarus",
            "Johannesburg, South Africa",
            "Belfast, United Kingdom",
            "Aswan, Egypt",
            "Anchorage, United States",
            "Yerevan, Armenia",
            "Luxembourg, Luxembourg",
            "Baku, Azerbaijan",
            "Addis Ababa, Ethiopia",
            "Santo Domingo, Dominican Republic",
            "Pyongyang, North Korea",
            "Almaty, Kazakhstan",
            "Mombasa, Kenya",
            "Valletta, Malta",
            "Antananarivo, Madagascar",
            "Miami, United States",
            "Bamako, Mali",
            "Ashgabat, Turkmenistan",
            "Oslo, Norway",
            "Milan, Italy",
            "Sao Paulo, Brazil",
            "Zurich, Switzerland",
            "Warsaw, Poland",
            "Atlanta, United States",
            "Guangzhou, China",
            "Philadelphia, United States",
            "Lima, Peru",
            "Brisbane, Australia",
            "Casablanca, Morocco",
            "Geneva, Switzerland",
            "Lyon, France",
            "San Jose, Costa Rica",
            "Lagos, Nigeria",
            "Detroit, United States",
            "Rotterdam, Netherlands",
            "Shenzhen, China",
            "Cologne, Germany",
            "Osaka, Japan",
            "Colombo, Sri Lanka",
            "Accra, Ghana",
            "St. Louis, United States",
            "Adelaide, Australia",
            "Porto, Portugal",
            "Birmingham, United Kingdom",
            "Turin, Italy",
            "Malmo, Sweden",
            "Ankara, Turkey",
            "Managua, Nicaragua",
            "Salt Lake City, United States",
            "Strasbourg, France",
            "Chengdu, China",
            "Nassau, Bahamas",
            "Lausanne, Switzerland",
            "Nuremberg, Germany",
            "Orlando, United States",
            "Ottawa, Canada",
            "Dresden, Germany",
            "Hangzhou, China",
            "Pretoria, South Africa",
            "Toulouse, France",
            "Bologna, Italy",
            "Canberra, Australia",
            "Nagoya, Japan",
            "Genoa, Italy",
            "Xian, China",
            "Nice, France",
            "Windhoek, Namibia",
            "Lalibela, Ethiopia",
            "Petra, Jordan",
            "Tashkent, Uzbekistan",
            "Santorini, Greece",
            "Siem Reap, Cambodia",
            "Kingston, Jamaica",
            "Brasilia, Brazil",
            "Liverpool, United Kingdom",
            "Bergen, Norway",
            "Harare, Zimbabwe",
            "Cancun, Mexico",
            "Cannes, France",
            "Samarkand, Uzbekistan",
            "Fukuoka, Japan",
            "Bagan, Myanmar",
            "Nottingham, United Kingdom",
            "Luxor, Egypt",
            "Mont St. Michel, France",
            "Lugano, Switzerland",
            "Sharm El Sheikh, Egypt",
            "Punta Cana, Domincan Republic",
            "Agra, India",
            "Varna, Bulgaria",
            "Honolulu, United States",
            "Chiang Mai, Thailand",
            "Haifa, Israel",
            "Thessaloniki, Greece",
            "Antalya, Turkey",
            "Batumi, Georgia",
            "The Hague, Netherlands",
            "Frankfurt, Germany",
            "Rabat, Morocco",
            "Cordoba, Spain",
            "Phuket, Thailand",
            "Salzburg, Austria",
            "Odessa, Ukraine",
            "Amman, Jordan",
            "Dubai, United Arab Emirates",
            "Kuala Lumpur, Malaysia",
            "Yalta, Ukraine",
            "Astana, Kazakhstan",
            "Interlaken, Switzerland",
            "Guatemala City, Guatemala",
            "Amritsar, India",
            "Ulaanbaatar, Mongolia",
            "Izmir, Turkey",
            "Volgograd, Russia",
            "Recife, Brazil",
            "Novosibirsk, Russia",
            "Manaus, Brazil",
            "Eilat, Israel",
            "Bali, Indonesia",
            "Riyadh, Saudi Arabia",
            "Doha, Qatar",
            "Vientiane, Laos",
            "Jericho, Palestine",
    };


    private String[] scientists = {
            "Louis Agassiz",
            "Maria Gaetana Agnesi",
            "Al-Battani",
            "Abu Nasr Al-Farabi",
            "Alhazen",
            "Jim Al-Khalili",
            "Muhammad ibn Musa al-Khwarizmi",
            "Mihailo Petrovic Alas",
            "Angel Alcala",
            "Salim Ali",
            "Luis Alvarez",
            "Andre Marie Ampere",
            "Anaximander",
            "Carl Anderson",
            "Mary Anning",
            "Virginia Apgar",
            "Archimedes",
            "Agnes Arber",
            "Aristarchus",
            "Aristotle",
            "Svante Arrhenius",
            "Oswald Avery",
            "Amedeo Avogadro",
            "Avicenna",
            "Charles Babbage",
            "Francis Bacon",
            "Alexander Bain",
            "John Logie Baird",
            "Joseph Banks",
            "Ramon Barba",
            "John Bardeen",
            "Charles Barkla",
            "Ibn Battuta",
            "William Bayliss",
            "George Beadle",
            "Arnold Orville Beckman",
            "Henri Becquerel",
            "Emil Adolf Behring",
            "Alexander Graham Bell",
            "Emile Berliner",
            "Claude Bernard",
            "Timothy John Berners-Lee",
            "Daniel Bernoulli",
            "Jacob Berzelius",
            "Henry Bessemer",
            "Hans Bethe",
            "Homi Jehangir Bhabha",
            "Alfred Binet",
            "Clarence Birdseye",
            "Kristian Birkeland",
            "Elizabeth Blackwell",
            "Alfred Blalock",
            "Katharine Burr Blodgett",
            "Franz Boas",
            "David Bohm",
            "Aage Bohr",
            "Niels Bohr",
            "Ludwig Boltzmann",
            "Max Born",
            "Carl Bosch",
            "Robert Bosch",
            "Jagadish Chandra Bose",
            "Satyendra Nath Bose",
            "Walther Wilhelm Georg Bothe",
            "Robert Boyle",
            "Lawrence Bragg",
            "Tycho Brahe",
            "Brahmagupta",
            "Hennig Brand",
            "Georg Brandt",
            "Wernher Von Braun",
            "J Harlen Bretz",
            "Louis de Broglie",
            "Alexander Brongniart",
            "Robert Brown",
            "Michael E. Brown",
            "Lester R. Brown",
            "Eduard Buchner",
            "Linda Buck",
            "William Buckland",
            "Georges-Louis Leclerc, Comte de Buffon",
            "Robert Bunsen",
            "Luther Burbank",
            "Jocelyn Bell Burnell",
            "Macfarlane Burnet",
            "Thomas Burnet",
            "Benjamin Cabrera",
            "Santiago Ramon y Cajal",
            "Rachel Carson",
            "George Washington Carver",
            "Henry Cavendish",
            "Anders Celsius",
            "James Chadwick",
            "Subrahmanyan Chandrasekhar",
            "Erwin Chargaff",
            "Noam Chomsky",
            "Steven Chu",
            "Leland Clark",
            "John Cockcroft",
            "Arthur Compton",
            "Nicolaus Copernicus",
            "Gerty Theresa Cori",
            "Charles-Augustin de Coulomb",
            "Jacques Cousteau",
            "Brian Cox",
            "Francis Crick",
            "James Croll",
            "Nicholas Culpeper",
            "Marie Curie",
            "Pierre Curie",
            "Georges Cuvier",
            "Adalbert Czerny",
            "Gottlieb Daimler",
            "John Dalton",
            "James Dwight Dana",
            "Charles Darwin",
            "Humphry Davy",
            "Peter Debye",
            "Max Delbruck",
            "Jean Andre Deluc",
            "Democritus",
            "René Descartes",
            "Rudolf Christian Karl Diesel",
            "Diophantus",
            "Paul Dirac",
            "Prokop Divis",
            "Theodosius Dobzhansky",
            "Frank Drake",
            "K. Eric Drexler",
            "John Eccles",
            "Arthur Eddington",
            "Thomas Edison",
            "Paul Ehrlich",
            "Albert Einstein",
            "Gertrude Elion",
            "Empedocles",
            "Eratosthenes",
            "Euclid",
            "Leonhard Euler",
            "Michael Faraday",
            "Pierre de Fermat",
            "Enrico Fermi",
            "Richard Feynman",
            "Emil Fischer",
            "Ronald Fisher",
            "Alexander Fleming",
            "Ambrose Fleming",
            "Howard Florey",
            "Henry Ford",
            "Lee De Forest",
            "Dian Fossey",
            "Leon Foucault",
            "Benjamin Franklin",
            "Rosalind Franklin",
            "Sigmund Freud",
            "Galen",
            "Galileo Galilei",
            "Francis Galton",
            "Luigi Galvani",
            "George Gamow",
            "Martin Gardner",
            "Carl Friedrich Gauss",
            "Murray Gell-Mann",
            "Sophie Germain",
            "Willard Gibbs",
            "William Gilbert",
            "Sheldon Lee Glashow",
            "Robert Goddard",
            "Maria Goeppert-Mayer",
            "Thomas Gold",
            "Jane Goodall",
            "Stephen Jay Gould",
            "Fritz Haber",
            "Ernst Haeckel",
            "Otto Hahn",
            "Albrecht von Haller",
            "Edmund Halley",
            "Thomas Harriot",
            "William Harvey",
            "Stephen Hawking",
            "Otto Haxel",
            "Werner Heisenberg",
            "Hermann von Helmholtz",
            "Jan Baptist von Helmont",
            "Joseph Henry",
            "Caroline Herschel",
            "John Herschel",
            "William Herschel",
            "Gustav Ludwig Hertz",
            "Heinrich Hertz",
            "Karl F. Herzfeld",
            "George de Hevesy",
            "Antony Hewish",
            "David Hilbert",
            "Maurice Hilleman",
            "Hipparchus",
            "Hippocrates",
            "Shintaro Hirase",
            "Dorothy Hodgkin",
            "Robert Hooke",
            "Frederick Gowland Hopkins",
            "William Hopkins",
            "Grace Murray Hopper",
            "Frank Hornby",
            "Jack Horner",
            "Bernardo Houssay",
            "Fred Hoyle",
            "Edwin Hubble",
            "Alexander von Humboldt",
            "Zora Neale Hurston",
            "James Hutton",
            "Christiaan Huygens",
            "Hypatia",
            "Ernesto Illy",
            "Ernst Ising",
            "Keisuke Ito",
            "Mae Carol Jemison",
            "Edward Jenner",
            "J. Hans D. Jensen",
            "Irene Joliot-Curie",
            "James Prescott Joule",
            "Percy Lavon Julian",
            "Michio Kaku",
            "Heike Kamerlingh Onnes",
            "Pyotr Kapitsa",
            "Friedrich August Kekulé",
            "Frances Kelsey",
            "Pearl Kendrick",
            "Johannes Kepler",
            "Abdul Qadeer Khan",
            "Omar Khayyam",
            "Alfred Kinsey",
            "Gustav Kirchoff",
            "Martin Klaproth",
            "Robert Koch",
            "Emil Kraepelin",
            "Thomas Kuhn",
            "Stephanie Kwolek",
            "Joseph-Louis Lagrange",
            "Jean-Baptiste Lamarck",
            "Hedy Lamarr",
            "Edwin Herbert Land",
            "Karl Landsteiner",
            "Pierre-Simon Laplace",
            "Max von Laue",
            "Antoine Lavoisier",
            "Ernest Lawrence",
            "Henrietta Leavitt",
            "Antonie van Leeuwenhoek",
            "Inge Lehmann",
            "Gottfried Leibniz",
            "Georges Lemaître",
            "Leonardo da Vinci",
            "Niccolo Leoniceno",
            "Aldo Leopold",
            "Rita Levi-Montalcini",
            "Claude Levi-Strauss",
            "Willard Frank Libby",
            "Justus von Liebig",
            "Carolus Linnaeus",
            "Joseph Lister",
            "John Locke",
            "Hendrik Antoon Lorentz",
            "Konrad Lorenz",
            "Ada Lovelace",
            "Percival Lowell",
            "Lucretius",
            "Charles Lyell",
            "Trofim Lysenko",
            "Ernst Mach",
            "Marcello Malpighi",
            "Jane Marcet",
            "Guglielmo Marconi",
            "Lynn Margulis",
            "Matthew Maury",
            "James Clerk Maxwell",
            "Ernst Mayr",
            "Barbara McClintock",
            "Lise Meitner",
            "Gregor Mendel",
            "Dmitri Mendeleev",
            "Franz Mesmer",
            "Antonio Meucci",
            "John Michell",
            "Albert Abraham Michelson",
            "Thomas Midgeley Jr.",
            "Milutin Milanković",
            "Maria Mitchell",
            "Mario Molina",
            "Thomas Hunt Morgan",
            "Samuel Morse",
            "Henry Moseley",
            "Ukichiro Nakaya",
            "John Napier",
            "Giulio Natta",
            "John Needham",
            "John von Neumann",
            "Thomas Newcomen",
            "Isaac Newton",
            "Charles Nicolle",
            "Florence Nightingale",
            "Tim Noakes",
            "Alfred Nobel",
            "Emmy Noether",
            "Christiane Nusslein-Volhard",
            "Bill Nye",
            "Hans Christian Oersted",
            "Georg Ohm",
            "J. Robert Oppenheimer",
            "Wilhelm Ostwald",
            "William Oughtred",
            "Blaise Pascal",
            "Louis Pasteur",
            "Wolfgang Ernst Pauli",
            "Linus Pauling",
            "Randy Pausch",
            "Ivan Pavlov",
            "Cecilia Payne-Gaposchkin",
            "Wilder Penfield",
            "Marguerite Perey",
            "William Perkin",
            "John Philoponus",
            "Jean Piaget",
            "Philippe Pinel",
            "Max Planck",
            "Pliny the Elder",
            "Karl Popper",
            "Beatrix Potter",
            "Joseph Priestley",
            "Proclus",
            "Claudius Ptolemy",
            "Pythagoras",
            "Adolphe Quetelet",
            "Harriet Quimby",
            "Thabit ibn Qurra",
            "C. V. Raman",
            "Srinivasa Ramanujan",
            "William Ramsay",
            "John Ray",
            "Prafulla Chandra Ray",
            "Francesco Redi",
            "Sally Ride",
            "Bernhard Riemann",
            "Wilhelm Röntgen",
            "Hermann Rorschach",
            "Ronald Ross",
            "Ibn Rushd",
            "Ernest Rutherford",
            "Carl Sagan",
            "Abdus Salam",
            "Jonas Salk",
            "Frederick Sanger",
            "Alberto Santos-Dumont",
            "Walter Schottky",
            "Erwin Schrödinger",
            "Theodor Schwann",
            "Glenn Seaborg",
            "Hans Selye",
            "Charles Sherrington",
            "Gene Shoemaker",
            "Ernst Werner von Siemens",
            "George Gaylord Simpson",
            "B. F. Skinner",
            "William Smith",
            "Frederick Soddy",
            "Mary Somerville",
            "Arnold Sommerfeld",
            "Hermann Staudinger",
            "Nicolas Steno",
            "Nettie Stevens",
            "William John Swainson",
            "Leo Szilard",
            "Niccolo Tartaglia",
            "Edward Teller",
            "Nikola Tesla",
            "Thales of Miletus",
            "Theon of Alexandria",
            "Benjamin Thompson",
            "J. J. Thomson",
            "William Thomson",
            "Henry David Thoreau",
            "Kip S. Thorne",
            "Clyde Tombaugh",
            "Susumu Tonegawa",
            "Evangelista Torricelli",
            "Charles Townes",
            "Youyou Tu",
            "Alan Turing",
            "Neil deGrasse Tyson",
            "Harold Urey",
            "Craig Venter",
            "Vladimir Vernadsky",
            "Andreas Vesalius",
            "Rudolf Virchow",
            "Artturi Virtanen",
            "Alessandro Volta",
            "Selman Waksman",
            "George Wald",
            "Alfred Russel Wallace",
            "John Wallis",
            "Ernest Walton",
            "James Watson",
            "James Watt",
            "Alfred Wegener",
            "John Archibald Wheeler",
            "Maurice Wilkins",
            "Thomas Willis",
            "E. O. Wilson",
            "Sven Wingqvist",
            "Sergei Winogradsky",
            "Carl Woese",
            "Friedrich Wöhler",
            "Wilbur and Orville Wright",
            "Wilhelm Wundt",
            "Chen-Ning Yang",
            "Ahmed Zewail"
    };

}
