server:
  port: 9090

spring:
  cloud:
    stream:
      bindings:
        persons:
          destination: persons.topic
          contentType: application/json

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: info,health,metrics
